// Customize const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';
export const GET_LANGUAGE = 'GET_LANGUAGE';
export const LANGUAGES = 'LANGUAGES';
export const SET_ADMIN_FOR_SUPPORT_TICKETS = "SET_ADMIN_FOR_SUPPORT_TICKETS";


// Right Sidebar
export const GET_QUE_JOBS = 'GET_QUE_JOBS';

// AppFilter
export const GET_DROPDOWN = 'GET_DROPDOWN';
export const POST_DROPDOWN = 'POST_DROPDOWN';
export const POST_PAGINATION = 'POST_PAGINATION';
export const GET_PAGINATION = 'GET_PAGINATION'

//Contact Module const
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const INVALID_TOKEN = 'INVALID_TOKEN';
export const COMPONENT_ALLOWED = 'COMPONENT_ALLOWED';
export const INVALID_RESPONSE = 'INVALID_RESPONSE';
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const GET_USER = 'GET_USER';
export const BEFORE_COMPONENT_ALLOWED = 'BEFORE_COMPONENT_ALLOWED';
export const DUPLICATE_SIM_IDS = 'DUPLICATE_SIM_IDS';
export const NEW_DATA_INSERTED = 'NEW_DATA_INSERTED';
export const TWO_FACTOR_AUTH = 'TWO_FACTOR_AUTH';
export const VERIFY_CODE = 'VERIFY_CODE';
export const CODE_VERIFIED = 'CODE_VERIFIED';
export const GOTO_LOGIN = 'GOTO_LOGIN';
export const LOGIN_HISTORY = 'LOGIN_HISTORY';

//Device const
export const DEVICES_LIST = 'DEVICES_LIST';
export const DEVICES_LIST_FOR_REPORT = 'DEVICES_LIST_FOR_REPORT';
export const SUSPEND_DEVICE = 'SUSPEND_DEVICE';
export const ACTIVATE_DEVICE = 'ACTIVATE_DEVICE';
export const CONNECT_DEVICE = "CONNECT_DEVICE";
export const EDIT_DEVICE = 'EDIT_DEVICE';
export const ADD_DATA_PLAN = 'ADD_DATA_PLAN';
export const TRANSFER_DEVICE = 'TRANSFER_DEVICE';
export const TRANSFER_USER = 'TRANSFER_USER';
export const MESSAGE_HANDLER = 'MESSAGE_HANDLER';
export const TRANSFER_HISTORY = 'TRANSFER_HISTORY';
export const SERVICES_HISTORY = 'SERVICES_HISTORY';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const ADD_DEVICE = 'ADD_DEVICE';
export const RELINK_DEVICE = 'RELINK_DEVICE';
export const REJECT_DEVICE = 'REJECT_DEVICE';
export const REJECT_RELINK_DEVICE = 'REJECT_RELINK_DEVICE';
export const NEW_DEVICES_LIST = 'NEW_DEVICES_LIST';
export const PRE_ACTIVATE_DEVICE = 'PRE_ACTIVATE_DEVICE';
export const SPIN_lOADING = 'SPIN_lOADING';
export const DELETE_UNLINK_DEVICE = 'DELETE_UNLINK_DEVICE';

export const NEW_REQUEST_LIST = 'NEW_REQUEST_LIST';
export const NEW_NOTIFICATION_LIST = 'NEW_NOTIFICATION_LIST';
export const USER_CREDITS = 'USER_CREDITS';
export const REJECT_REQUEST = 'REJECT_REQUEST'
export const REJECT_SERVICES_REQUEST = 'REJECT_SERVICES_REQUEST'
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST'
export const ACCEPT_SERVICE_REQUEST = 'ACCEPT_SERVICE_REQUEST'
export const GET_CANCEL_REQUEST = 'GET_CANCEL_REQUEST'
export const CANCEL_EXTENDED_SERVICE = 'CANCEL_EXTENDED_SERVICE'


// Bulk Devices
export const BULK_LOADING = 'BULK_LOADING';
export const BULK_DEVICES_LIST = 'BULK_DEVICES_LIST';
export const BULK_SUSPEND_DEVICES = 'BULK_SUSPEND_DEVICES';
export const BULK_ACTIVATE_DEVICES = 'BULK_ACTIVATE_DEVICES';
export const BULK_HISTORY = 'BULK_HISTORY';
export const BULK_HISTORY_LOADING = 'BULK_HISTORY_LOADING';
export const BULK_USERS = 'BULK_USERS';
export const BULK_PUSH_APPS = 'BULK_PUSH_APPS';
export const BULK_PULL_APPS = 'BULK_PULL_APPS';
export const SET_PUSH_APPS = 'SET_PUSH_APPS';
export const SET_PULL_APPS = 'SET_PULL_APPS';
export const SET_SELECTED_BULK_DEVICES = 'SET_SELECTED_BULK_DEVICES';
export const UNLINK_BULK_DEVICES = 'UNLINK_BULK_DEVICES';
export const WIPE_BULK_DEVICES = 'WIPE_BULK_DEVICES';
export const CLOSE_RESPONSE_MODAL = 'CLOSE_RESPONSE_MODAL';
export const APPLY_BULK_POLICY = 'APPLY_BULK_POLICY';
export const SET_BULK_MESSAGE = "SET_BULK_MESSAGE"
export const SET_BULK_DATA = "SET_BULK_DATA"
export const SEND_BULK_MESSAGE = "SEND_BULK_MESSAGE"
export const UPDATE_BULK_MESSAGE = "UPDATE_BULK_MESSAGE"
export const HANDLE_BULK_WIPE_PASS = "HANDLE_BULK_WIPE_PASS"
export const GET_BULK_MSGS = "GET_BULK_MSGS"
export const DELETE_BULK_MSG = "DELETE_BULK_MSG"


//Dealer const
export const DEALER_LOADING = 'DEALER_LOADING';
export const DEALERS_LIST = 'DEALERS_LIST';
export const ALL_TO_ALL_DEALERS = 'ALL_TO_ALL_DEALERS';
export const EDIT_DEALER = 'EDIT_DEALER';
export const CONNECT_EDIT_DEALER = 'CONNECT_EDIT_DEALER';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const DELETE_DEALERS = 'DELETE_DEALERS';
export const CONNECT_DELETE_DEALER = 'CONNECT_DELETE_DEALER';
export const UNDO_DEALER = 'UNDO_DEALER';
export const CONNECT_UNDO_DEALER = 'CONNECT_UNDO_DEALER';
export const SUSPEND_DEALERS = 'SUSPEND_DEALERS';
export const CONNECT_SUSPEND_DEALER = 'CONNECT_SUSPEND_DEALER';
export const ACTIVATE_DEALER = 'ACTIVATE_DEALER';
export const CONNECT_ACTIVATE_DEALER = 'CONNECT_ACTIVATE_DEALER';
export const ADD_DEALER = 'ADD_DEALER';
export const DEALERS_LIST_IN_SDEALER = 'DEALERS_LIST_IN_SDEALER';
export const CHANGE_TIMEZONE = 'CHANGE_TIMEZONE';
export const HANDLE_ADD_DEALER_MODAL = 'HANDLE_ADD_DEALER_MODAL';
export const ADD_DEALER_LOADING = 'ADD_DEALER_LOADING';

// Dealer Connect
export const DEALER_DETAILS = 'DEALER_DETAILS';
export const DEALER_PAYMENT_HISTORY = 'DEALER_PAYMENT_HISTORY';
export const SET_DEALER_LIMIT = 'SET_DEALER_LIMIT';
export const SET_DEMOS_LIMIT = 'SET_DEMOS_LIMIT';
export const DEALER_SALES_HISTORY = 'DEALER_SALES_HISTORY';
export const DEALER_DOMAINS = 'DEALER_DOMAINS'
export const CONNECT_DEALER_LOADING = 'CONNECT_DEALER_LOADING'
export const DEALER_ACCOUNT_STATUS = 'DEALER_ACCOUNT_STATUS';
export const CD_PERMISSION_DOMAINS = 'CD_PERMISSION_DOMAINS'; // CONNECT DEALER (CD)
export const ERROR_PERMISSION_DOMAINS = 'ERROR_PERMISSION_DOMAINS';
export const DEALER_DOMAINS_LOADING = 'DEALER_DOMAINS_LOADING'

// Apk const
export const APK_LOADING = 'APK_LOADING';
export const APK_LIST = 'APK_LIST';
export const UNLINK_APK = 'UNLINK_APK';
export const ADD_APK = 'ADD_APK';
export const EDIT_APK = 'EDIT_APK';
export const APK_STATUS_CHANGED = 'APK_STATUS_CHANGED';
export const PERMISSION_SAVED = 'PERMISSION_SAVED';
export const RESET_UPLOAD_FORM = 'RESET_UPLOAD_FORM';
export const RESET_AUTH_UPDATE = 'RESET_AUTH_UPDATE';
export const CHECK_APK_NAME = 'CHECK_APK_NAME';
export const AUTHENTICATE_UPDATE_USER = 'AUTHENTICATE_UPDATE_USER';

// Domains
export const GET_DOMAINS = 'GET_DOMAINS';
export const PERMISSION_DOMAINS = 'PERMISSION_DOMAINS';

// Connect Device
export const GET_DEVICE_BILLING_HISTORY = 'GET_DEVICE_BILLING_HISTORY';
export const RESET_DEVICE = 'RESET_DEVICE';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const GET_DEVICE_DETAILS = 'GET_DEVICE_DETAILS';
export const DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND';
export const GET_DEVICE_LIST = 'GET_DEVICE_LIST';
export const CLEAR_APPLICATIONS = 'CLEAR_APPLICATIONS';
export const CLEAR_STATE = 'CLEAR_STATE';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_DEVICE_APPS = 'GET_DEVICE_APPS';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_DEVICE_HISTORIES = 'GET_DEVICE_HISTORIES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_APPS_PERMISSIONS = 'GET_APPS_PERMISSIONS';
export const DEVICE_SYNCED = 'device_synced';
export const SUBMIT_PASSWORD = 'SUBMIT_PASSWORD';
export const GUEST_PASSWORD = 'guest_password';
export const ENCRYPTED_PASSWORD = 'encrypted_password';
export const DURESS_PASSWORD = 'duress_password';
export const ADMIN_PASSWORD = 'admin_password';
export const ACTIVATE_DEVICE2 = 'ACTIVATE_DEVICE2';
export const SUSPEND_DEVICE2 = 'SUSPEND_DEVICE2';
export const GET_USER_ACC_ID = 'GET_USER_ACC_ID';
export const FLAG_DEVICE = 'FLAG_DEVICE';
export const UNFLAG_DEVICE = 'UNFLAG_DEVICE';
export const WIPE_DEVICE = 'WIPE_DEVICE';
export const CHECKPASS = 'CHECKPASS';
export const CHECK_BACKUP_PASS = 'CHECK_BACKUP_PASS';
export const CHECK_BULK_PASS = 'CHECK_BULK_PASS';
export const RESET_BULK_FLAG = 'RESET_BULK_FLAG';
export const GET_DEALER_APPS = 'GET_DEALER_APPS';
export const HANDLE_CHECK_EXTENSION = 'HANDLE_CHECK_EXTENSION';
export const HANDLE_CHECK_ALL_EXTENSION = 'HANDLE_CHECK_ALL_EXTENSION';
export const HANDLE_CHECK_APP_POLICY = 'HANDLE_CHECK_APP_POLICY';
export const HANDLE_CHECK_SYSTEM_PERMISSIONS = 'HANDLE_CHECK_SYSTEM_PERMISSIONS';
export const HANDLE_CHECK_ALL_APP_POLICY = 'HANDLE_CHECK_ALL_APP_POLICY';
export const HANDLE_APPS_GOTTED = 'HANDLE_APPS_GOTTED';

export const SHOW_PUSH_APPS_MODAL = 'SHOW_PUSH_APPS_MODAL';
export const UNDO_EXTENSIONS = 'UNDO_EXTENSIONS';
export const REDO_EXTENSIONS = 'REDO_EXTENSIONS';
export const HANDLE_CHECK_CONTROL = 'HANDLE_CHECK_CONTROL';
export const HANDLE_CHECK_MAIN_SETTINGS = 'HANDLE_CHECK_MAIN_SETTINGS';
export const HANDLE_CHECK_SECURE_SETTINGS = 'HANDLE_CHECK_SECURE_SETTINGS';

export const UNDO_CONTROLS = 'UNDO_CONTROLS';
export const REDO_CONTROLS = 'REDO_CONTROLS';

export const PUSH_APP_CHECKED = 'PUSH_APP_CHECKED';
export const RESET_PUSH_APPS = 'RESET_PUSH_APPS';
export const HANDLE_CHECK_ALL_PUSH_APPS = 'HANDLE_CHECK_ALL_PUSH_APPS';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const HANDLE_CHECK_APP = 'HANDLE_CHECK_APP';
export const HANDLE_CHECK_ALL = 'HANDLE_CHECK_ALL';
export const CHECK_HANDLE_ALL_POLICY = 'CHECK_HANDLE_ALL_POLICY';

export const PUSH_APPS = 'PUSH_APPS';
export const PULL_APPS = 'PULL_APPS';
export const UNDO_APPS = "UNDO_APPS";
export const REDO_APPS = 'REDO_APPS';
export const SHOW_PULL_APPS_MODAL = 'SHOW_PULL_APPS_MODAL';
export const CHAT_ID_SETTINGS = 'CHAT_ID_SETTINGS';
export const ENABLE_PWD_CONFIRM = 'ENABLE_PWD_CONFIRM';

export const SAVE_POLICY = 'SAVE_POLICY';
export const APPLY_POLICY = 'APPLY_POLICY';
export const PACKAGE_PERMISSION_SAVED = 'PACKAGE_PERMISSION_SAVED';
export const DELETE_PACKAGE = 'DELETE_PACKAGE';
export const MODIFY_ITEM_PRICE = 'MODIFY_ITEM_PRICE';
export const POLICY_PERMISSION_SAVED = 'POLICY_PERMISSION_SAVED';
export const GET_SYSTEM_PERMISSIONS = 'GET_SYSTEM_PERMISSIONS';

export const APPLY_SETTINGS = 'APPLY_SETTINGS';

export const SETTINGS_APPLIED = 'SETTINGS_APPLIED';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
// export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const SHOW_HISTORY_MODAL = 'SHOW_HISTORY_MODAL';
export const SHOW_SAVE_PROFILE_MODAL = 'SHOW_SAVE_PROFILE_MODAL';
export const HANDLE_PROFILE_INPUT = 'HANDLE_PROFILE_INPUT';
export const POLICY = 'policy';
export const PROFILE = 'profile';
export const SAVE_PROFILE = 'SAVE_PROFILE';
export const UNLINK_DEVICE = 'UNLINK_DEVICE';
export const HANDLE_POLICY_STATUS = 'HANDLE_POLICY_STATUS';
export const EDIT_POLICY = 'EDIT_POLICY';
export const SAVE_POLICY_CHANGES = 'SAVE_POLICY_CHANGES';
export const HIDE_POLICY_CONFIRM = 'HIDE_POLICY_CONFIRM';

export const LOADING = 'LOADING';
export const IMPORT_CSV = 'IMPORT_CSV';
export const GET_SIM_IDS = 'GET_SIM_IDS';
export const GET_CHAT_IDS = 'GET_CHAT_IDS';
export const GET_PGP_EMAILS = 'GET_PGP_EMAILS';
export const GET_USED_PGP_EMAILS = 'GET_USED_PGP_EMAILS';
export const GET_USED_CHAT_IDS = 'GET_USED_CHAT_IDS';
export const GET_USED_SIM_IDS = 'GET_USED_SIM_IDS';
export const RELEASE_CSV = 'RELEASE_CSV';
export const GET_IMIE_HISTORY = 'GET_IMIE_HISTORY';
export const WRITE_IMEI = 'WRITE_IMEI';
export const CREATE_BACKUP_DB = 'CREATE_BACKUP_DB';



// Policy const
export const GET_POLICIES = 'GET_POLICIES'
export const DEFAULT_POLICY_CHANGE = 'DEFAULT_POLICY_CHANGE';
export const ADD_APPS_TO_POLICIES = 'ADD_APPS_TO_POLICIES';
export const REMOVE_APPS_FROM_POLICIES = 'REMOVE_APPS_FROM_POLICIES';
export const CHECK_TOGGLE_BUTTONS = 'CHECK_TOGGLE_BUTTONS';
export const RESET_POLICY = 'RESET_POLICY';
export const RESET_ADD_POLICY_FORM = 'RESET_ADD_POLICY_FORM';


// Users const
export const SAVE_USERS = 'SAVE_USERS'
export const EDIT_USERS = 'EDIT_USERS'
export const LOAD_USER = 'LOAD_USER'
export const USERS_LIST = 'USERS_LIST'
export const INVOICE_ID = 'INVOICE_ID'
export const DEALER_USERS = 'DEALER_USERS'
export const DELETE_USER = 'DELETE_USER'
export const UNDO_DELETE_USER = 'UNDO_DELETE_USER'

//App Market Constants
export const TRANSFER_APPS = 'TRANSFER_APPS'
export const REMOVE_APPS = 'REMOVE_APPS'
export const GET_MARKET_APPS = 'GET_MARKET_APPS'
export const UNINSTALL_PERMISSION_CHANGED = 'UNINSTALL_PERMISSION_CHANGED'


// Socket Actions
export const FINISHED_PUSH_APPS = 'FINISHED_PUSH_APPS';
export const FINISHED_PULL_APPS = 'FINISHED_PULL_APPS';
export const FINISHED_POLICY = 'FINISHED_POLICY';
export const FINISHED_WIPE = 'FINISHED_WIPE';
export const FINISHED_POLICY_STEP = 'FINISHED_POLICY_STEP';
export const FINISHED_IMEI = 'FINISHED_IMEI';
export const IN_PROCESS = 'IN_PROCESS';
export const SINGLE_APP_PUSHED = 'SINGLE_APP_PUSHED';
export const SINGLE_APP_PULLED = 'SINGLE_APP_PULLED';
export const GET_APP_JOBS = 'GET_APP_JOBS';


export const SHOW_BACKUP_MODAL = 'SHOW_BACKUP_MODAL';

export const SAVE_ID_PRICES = 'SAVE_ID_PRICES';
export const SAVE_PACKAGE = 'SAVE_PACKAGE';
export const EDIT_PACKAGE = 'EDIT_PACKAGE';
export const GET_PACKAGES = 'GET_PACKAGES';
export const GET_HARDWARE = 'GET_HARDWARE';
export const GET_PARENT_PACKAGES = 'GET_PARENT_PACKAGES';
export const GET_PARENT_HARDWARES = 'GET_PARENT_HARDWARES';
export const GET_PRODUCT_PRICES = 'GET_PRODUCT_PRICES';
export const PURCHASE_CREDITS = 'PURCHASE_CREDITS';
export const GET_PRICES = 'GET_PRICES';
export const SET_PRICE = 'SET_PRICE';
export const RESET_PRICE = 'RESET_PRICE';
export const RESYNC_IDS = 'RESYNC_IDS';



// Sim Module (connect device)
export const ADD_SIM_REGISTER = "ADD_SIM_REGISTER";
export const GET_SIMS = "GET_SIMS";
export const UPDATE_SIM = "UPDATE_SIM";
export const DELETE_SIM = "DELETE_SIM";
export const SIM_HISTORY = "SIM_HISTORY";
export const GET_UNREG_SIMS = "GET_UNREG_SIMS";
export const SIM_LOADING = "SIM_LOADING";


export const RECEIVE_SIM_DATA = "RECEIVE_SIM_DATA";


// Agent constants (Dealer Agents)
export const AGENT_LIST = 'AGENT_LIST';
export const SAVE_AGENT = 'SAVE_AGENT';
export const DELETE_AGENT = 'DELETE_AGENT';
export const EDIT_AGENT = 'EDIT_AGENT';
export const UPDATE_AGENT = 'UPDATE_AGENT';
export const CHANGE_AGENT_STATUS = 'CHANGE_AGENT_STATUS';
export const RESET_AGENT_PWD = 'RESET_AGENT_PWD'



// Dashboard constants

export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';

//Reporting
export const PRODUCT_REPORT = 'PRODUCT_REPORT';
export const INVOICE_REPORT = 'INVOICE_REPORT';
export const PAYMENT_HISTORY_REPORT = 'PAYMENT_HISTORY_REPORT';
export const HARDWARE_REPORT = 'HARDWARE_REPORT';
export const SALES_REPORT = 'SALES_REPORT';
export const GRACE_DAYS_REPORT = 'GRACE_DAYS_REPORT';

export const LATEST_PAYMENT_HISTORY = 'LATEST_PAYMENT_HISTORY';
export const GET_OVERDUE_DETAILS = 'GET_OVERDUE_DETAILS';


/**
 * @author Usman Hafeez
 * @description Manage data constants
 */

export const RESET_IDS = 'RESET_IDS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const RESET_ADD_PRODUCT_PROPS = 'RESET_ADD_PRODUCT_PROPS';
export const VALIDATE_ICCID = 'VALIDATE_ICCID';
export const RESET_CHAT_PIN = 'RESET_CHAT_PIN';
export const RESET_PGP_LIMIT = 'RESET_PGP_LIMIT';
export const CHANGE_SCHAT_ACCOUNT_STATUS = 'CHANGE_SCHAT_ACCOUNT_STATUS';
// Tickets
export const GENERATE_SUPPORT_TICKET = 'GENERATE_SUPPORT_TICKET';
export const UPDATE_SUPPORT_TICKET_NOTIFICATIONS = 'UPDATE_SUPPORT_TICKET_NOTIFICATIONS';
export const SET_CURRENT_TICKET_ID = 'SET_CURRENT_TICKET_ID';
export const RESET_CURRENT_TICKET_ID = 'RESET_CURRENT_TICKET_ID';
export const GENERATE_SUPPORT_TICKET_SOCKET = 'GENERATE_SUPPORT_TICKET_SOCKET';
export const SUPPORT_TICKET_REPLY = 'SUPPORT_TICKET_REPLY';
export const UPDATE_SUPPORT_TICKET_REPLY = 'UPDATE_SUPPORT_TICKET_REPLY';
export const UPDATE_SUPPORT_TICKET_REPLY_SOCKET = 'UPDATE_SUPPORT_TICKET_REPLY_SOCKET';
export const GET_SUPPORT_TICKET = 'GET_SUPPORT_TICKET';
export const GET_SUPPORT_TICKET_REPLY = 'GET_SUPPORT_TICKET_REPLY';
export const UPDATE_TICKET_NOTIFICATION_STATUS = 'UPDATE_TICKET_NOTIFICATION_STATUS';
export const UPDATE_NOTIFICATION_STATUS = 'UPDATE_NOTIFICATION_STATUS';
export const CLOSE_SUPPORT_TICKET = 'CLOSE_SUPPORT_TICKET';
export const DELETE_SUPPORT_TICKET = 'DELETE_SUPPORT_TICKET';
// system Messages
export const GENERATE_SYSTEM_MESSAGE = 'GENERATE_SYSTEM_MESSAGE';
export const GENERATE_SYSTEM_MESSAGE_SOCKET = 'GENERATE_SYSTEM_MESSAGE_SOCKET';
export const GET_SYSTEM_MESSAGE = 'GET_SYSTEM_MESSAGE';
export const GENERATE_SUPPORT_SYSTEM_MESSAGE = 'GENERATE_SUPPORT_SYSTEM_MESSAGE';
export const SUPPORT_SYSTEM_MESSAGES_SOCKET = 'SUPPORT_SYSTEM_MESSAGES_SOCKET';
export const GET_SUPPORT_SYSTEM_MESSAGE = 'GET_SUPPORT_SYSTEM_MESSAGE';
export const GET_RECEIVED_SUPPORT_SYSTEM_MESSAGES = 'GET_RECEIVED_SUPPORT_SYSTEM_MESSAGES';
export const GET_SUPPORT_SYSTEM_MESSAGE_NOTIFICATION = 'GET_SUPPORT_SYSTEM_MESSAGE_NOTIFICATION';
export const UPDATE_SUPPORT_SYSTEM_MESSAGE_NOTIFICATION = 'UPDATE_SUPPORT_SYSTEM_MESSAGE_NOTIFICATION';
export const ADD_SUPPORT_SYSTEM_MESSAGE_NOTIFICATION = 'ADD_SUPPORT_SYSTEM_MESSAGE_NOTIFICATION';
export const SYSTEM_SUPPORT_MESSAGE_RECEIVED = 'SYSTEM_SUPPORT_MESSAGE_RECEIVED';

//support live chat
export const SEND_SUPPORT_LIVE_CHAT_MESSAGE = 'SEND_SUPPORT_LIVE_CHAT_MESSAGE';
export const GET_SUPPORT_LIVE_CHAT_CONVERSATION = 'GET_SUPPORT_LIVE_CHAT_CONVERSATION';
export const GET_SUPPORT_LIVE_CHAT_MESSAGES = 'GET_SUPPORT_LIVE_CHAT_MESSAGES';
export const GET_SUPPORT_LIVE_CHAT_PREVIOUS_MESSAGES = 'GET_SUPPORT_LIVE_CHAT_PREVIOUS_MESSAGES';

//sidebar
export const SET_SUPPORT_PAGE = 'SET_SUPPORT_PAGE';
export const RESET_SUPPORT_PAGE = 'RESET_SUPPORT_PAGE';
export const SET_CURRENT_SYSTEM_MESSAGE_ID = 'SET_CURRENT_SYSTEM_MESSAGE_ID';
export const RESET_CURRENT_SYSTEM_MESSAGE_ID = 'RESET_CURRENT_SYSTEM_MESSAGE_ID';
export const SET_CURRENT_SUPPORT_TICKET_ID = 'SET_CURRENT_SUPPORT_TICKET_ID';
export const RESET_CURRENT_SUPPORT_TICKET_ID = 'RESET_CURRENT_SUPPORT_TICKET_ID';

// microservice current state
export const MICRO_SERVICE_RUNNING = 'MICRO_SERVICE_RUNNING';
export const MICRO_SERVICE_STOPPED = 'MICRO_SERVICE_STOPPED';

//support live chat constants
export const SUPPORT_LIVE_CHAT_MESSAGE_RECEIVED = 'SUPPORT_LIVE_CHAT_MESSAGE_RECEIVED';
export const SUPPORT_LIVE_CHAT_I_AM_TYPING = 'SUPPORT_LIVE_CHAT_I_AM_TYPING';
export const SUPPORT_LIVE_CHAT_I_STOPPED_TYPING = 'SUPPORT_LIVE_CHAT_I_STOPPED_TYPING';
export const SUPPORT_LIVE_CHAT_USER_TYPING = 'SUPPORT_LIVE_CHAT_USER_TYPING';
export const SUPPORT_LIVE_CHAT_USER_STOPPED_TYPING = 'SUPPORT_LIVE_CHAT_USER_STOPPED_TYPING';
export const SUPPORT_LIVE_CHAT_CONVERSATION_DELETED = 'SUPPORT_LIVE_CHAT_CONVERSATION_DELETED';
export const SUPPORT_LIVE_CHAT_MESSAGE_DELETED = 'SUPPORT_LIVE_CHAT_MESSAGE_DELETED';
export const SUPPORT_LIVE_CHAT_NOTIFICATIONS = 'SUPPORT_LIVE_CHAT_NOTIFICATIONS';
export const SUPPORT_LIVE_CHAT_NOTIFICATION_NEW_MESSAGE = 'SUPPORT_LIVE_CHAT_NOTIFICATION_NEW_MESSAGE';
export const SUPPORT_LIVE_CHAT_SET_CONVERSATION = 'SUPPORT_LIVE_CHAT_SET_CONVERSATION';
export const SUPPORT_LIVE_CHAT_RESET_CONVERSATION = 'SUPPORT_LIVE_CHAT_RESET_CONVERSATION';
export const SUPPORT_LIVE_CHAT_READ_MESSAGES = 'SUPPORT_LIVE_CHAT_READ_MESSAGES';
export const SUPPORT_LIVE_CHAT_SET_CONVERSATION_ON_MESSAGE_SENT = 'SUPPORT_LIVE_CHAT_SET_CONVERSATION_ON_MESSAGE_SENT';


//STANDALONE SIM

export const STAND_ALONE_LIST = 'STAND_ALONE_LIST';
export const CHANGE_SIM_STATUS = 'CHANGE_SIM_STATUS';
export const ADD_STANDALONE_SIM = 'ADD_STANDALONE_SIM';
