export const Button_Modify = "button.Modify";
export const Button_Delete = "button.Delete";
export const Button_Activate = "button.Activate";
export const Button_Active = "button.Active";
export const Button_Connect = "button.Connect";
export const Button_Yes = "button.Yes";
export const Button_No = "button.No";
export const Button_Yess = "button.Yess";
export const Button_Noo = "button.Noo";
export const Button_Ok = "button.ok";
export const Button_Cancel = "button.Cancel";
export const Button_Suspend = "button.Suspend";
export const Button_Unsuspend = "button.Unsuspend";
export const Button_Edit = "button.Edit";
export const Button_passwordreset = "button.passwordreset";
export const Button_submit = "button.submit";
export const Button_Flag = "button.Flag";
export const Button_UNFLAG = "button.UNFLAG";
export const Button_SetPassword = "button.SetPassword";
export const Button_Apply = "button.Apply";
export const Button_Undelete = "button.Undelete";
export const Button_Undo = "button.Undo";
export const Button_Redo = "button.Redo";
export const Button_Clear = "button.Clear";
export const Button_Refresh = "button.Refresh";
export const Button_Next = "button.Next";
export const Button_previous = "button.previous";
export const Button_Add_Dealer = "button.AddDealer";
export const Button_Add_S_dealer = "button.AddS-dealer"
export const Button_Add_Admin = "button.add.admin"
export const Button_UploadApk = "button.UploadApk";
export const Button_Save = "button.Save";
export const Button_Update = "button.Update";
export const Button_Open = "button.Open";
export const Button_Sample = "button.Sample";
export const Button_Import = "button.Import";
export const Button_Export = "button.Export";
export const Button_Release = "button.Release";
export const Button_View = "button.View";
export const Button_ChangePassword = "button.ChangePassword";
export const Button_ChangeEmail = "button.ChangeEmail";
export const Button_AddPolicy = "button.AddPolicy";
export const Button_Add = "button.Add";
export const Button_AddExceptSelected = "button.AddExceptSelected";
export const Button_AddAll = "button.AddAll";
export const Button_RemoveAll = "button.RemoveAll";
export const Button_RemoveExcept = "button.RemoveExcept";
export const Button_BackupNow = "button.BackupNow";
export const Button_DeleteUser = "button.DeleteUser";
export const Button_AddApps = "button.AddApps";
export const Button_Push = "button.Push";
export const Button_LoadProfile = "button.LoadProfile";
export const Button_LoadPolicy = "button.LoadPolicy";
export const Button_IMEI = "button.IMEI";
export const Button_Pull = "button.Pull";
export const Button_SaveProfile = "button.SaveProfile";
export const Button_Activity = "button.Activity"; // ACTIVITY
export const Button_SIM = "button.SIM";
export const Button_Transfer = "button.Transfer";
export const Button_WipeDevice = "button.WipeDevice";
export const Button_Unlink = "button.Unlink";
export const Button_Add_Device = "button.Add.Device";
export const Button_Uninstall = "button.Uninstall"; // Uninstall 

export const Button_BUY = "button.buy.id"; // Buy
export const Button_SET_PRICE = "button.set.prices.id"; // Set Price
export const Button_SET = "button.set.id"; // SET
export const Button_UNSET = "button.unset.id"; // UNSET
export const Button_DOWNLOAD = "button.download.id"; // Download
export const Button_Back = "button.back.id"; // Back

export const Switch_Button_Uninstall = "switch.button.uninstall.id"; // Uninstall
export const Button_Save_Changes = "button.save.changes"; // Save Changes


export const Button_Remove = "button.Remove"; // Remove
export const Button_DeleteExceptSelected = "button.DeleteExceptSelected"; // Delete Except Selected
export const Button_Add_User = "button.add.user" // Add User
export const Button_Confirm = "button.Confirm.id";
export const Button_Decline = "button.decline.id";
export const Button_ACCEPT = "Button_ACCEPT.id";
export const Button_On = "button.On.id"; // On
export const Button_Off = "button.off.id"; // Off