// export const DEVICE_ID = "tableHeadings.DEVICEID";
export const USER_ID = "usersColHeading.USERID";
export const USER_NAME = "usersColHeading.NAME";
export const USER_EMAIL = "usersColHeading.EMAIL";
export const USER_DATE_REGISTERED = "usersColHeading.DATEREGISTERED";
export const USER_TOKEN =  "usersColHeading.TOKENS";
export const DEVICES = "usersColHeading.DEVICES";
export const EDIT_USER = "edit.user.id"; // Edit User
export const DELETE_USER = "DELETE.USER.id"; // DELETE USER
export const DO_YOU_WANT_TO_DELETE_USER = "Do.you.want.to.DELETE.user.id"; // Do you want to DELETE user 
export const UNDO = "UNDO.id"; // UNDO
export const DO_YOU_WANT_TO_UNDO_USER = "Do.you.want.to.UNDO.user.id"; // Do you want to UNDO user 
