// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

// AppFilter
export const GET_DROPDOWN = 'GET_DROPDOWN';
export const POST_DROPDOWN = 'POST_DROPDOWN';
export const POST_PAGINATION = 'POST_PAGINATION';
export const GET_PAGINATION = 'GET_PAGINATION'

//Contact Module const
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const INVALID_TOKEN = 'INVALID_TOKEN';
export const COMPONENT_ALLOWED = 'COMPONENT_ALLOWED';
export const INVALID_RESPONSE = 'INVALID_RESPONSE';
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const GET_USER = 'GET_USER';
export const BEFORE_COMPONENT_ALLOWED = 'BEFORE_COMPONENT_ALLOWED';
export const DUPLICATE_SIM_IDS = 'DUPLICATE_SIM_IDS';
export const NEW_DATA_INSERTED = 'NEW_DATA_INSERTED';
export const TWO_FACTOR_AUTH = 'TWO_FACTOR_AUTH';
export const VERIFY_CODE = 'VERIFY_CODE';
export const CODE_VERIFIED = 'CODE_VERIFIED';
export const GOTO_LOGIN = 'GOTO_LOGIN';
export const RESET_REBOOT_CONFIRM = 'RESET_REBOOT_CONFIRM';
export const VERIFY_PASSWORD = 'VERIFY_PASSWORD';
export const RESET_PASSWORD_VARIFIED = 'RESET_PASSWORD_VARIFIED';


// WhiteLabels const
export const GET_ALL_WHITE_LABELS = 'GET_ALL_WHITE_LABELS';

export const GET_WHITE_LABELS = 'GET_WHITE_LABELS';
export const EDIT_WHITE_LABEL_INFO = 'EDIT_WHITE_LABEL_INFO';
export const WHITE_LABEL_BACKUPS = 'WHITE_LABEL_BACKUPS';
export const GET_FILE = 'GET_FILE';
export const SAVE_ID_PRICES = 'SAVE_ID_PRICES';
export const SAVE_PACKAGE = 'SAVE_PACKAGE';
export const SAVE_HARDWARE = 'SAVE_HARDWARE';
export const GET_PRICES = 'GET_PRICES';
export const SET_PRICE = 'SET_PRICE';
export const RESET_PRICE = 'RESET_PRICE';
export const SAVE_BACKUP = 'SAVE_BACKUP';
export const START_BACKUP_LOADING = 'START_BACKUP_LOADING';

export const DELETE_PAKAGE = 'DELETE_PAKAGE'
export const DELETE_HARDWARE = 'DELETE_HARDWARE'
export const GET_PACKAGES = 'GET_PACKAGES'
export const GET_HARDWARES = 'GET_HARDWARES'
export const EDIT_HARDWARE = 'EDIT_HARDWARE'
export const REJECT_REQUEST = 'REJECT_REQUEST'
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST'
export const RESTART_WHITELABEL = 'RESTART_WHITELABEL';
export const GET_DOMAINS = 'GET_DOMAINS'
export const DELETE_DOMAINS = 'DELETE_DOMAINS'
export const ADD_DOMAIN = 'ADD_DOMAIN'
export const EDIT_DOMAIN = 'EDIT_DOMAIN'

//Device const
export const DEVICES_LIST = 'DEVICES_LIST';
export const SUSPEND_DEVICE = 'SUSPEND_DEVICE';
export const ACTIVATE_DEVICE = 'ACTIVATE_DEVICE';
export const CONNECT_DEVICE = "CONNECT_DEVICE";
export const EDIT_DEVICE = 'EDIT_DEVICE';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const ADD_DEVICE = 'ADD_DEVICE';
export const REJECT_DEVICE = 'REJECT_DEVICE';
export const NEW_REQUEST_LIST = 'NEW_REQUEST_LIST';
export const PRE_ACTIVATE_DEVICE = 'PRE_ACTIVATE_DEVICE';
export const SPIN_lOADING = 'SPIN_lOADING';
export const DELETE_UNLINK_DEVICE = 'DELETE_UNLINK_DEVICE';
export const OFFLINE_DEVICES_STATUS = 'OFFLINE_DEVICES_STATUS';


//Dealer const
export const DEALERS_LIST = 'DEALERS_LIST';
export const SUSPEND_DEALERS = 'SUSPEND_DEALERS';
export const EDIT_DEALER = 'EDIT_DEALER';
export const DELETE_DEALERS = 'DELETE_DEALERS';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const ACTIVATE_DEALER = 'ACTIVATE_DEALER';
export const UNDO_DEALER = 'UNDO_DEALER';
export const ADD_DEALER = 'ADD_DEALER';

// Apk const
export const APK_LIST = 'APK_LIST';
export const UNLINK_APK = 'UNLINK_APK';
export const ADD_APK = 'ADD_APK';
export const EDIT_APK = 'EDIT_APK';
export const APK_STATUS_CHANGED = 'APK_STATUS_CHANGED';
export const PERMSSION_SAVED = 'PERMSSION_SAVED';
export const RESET_UPLOAD_FORM = 'RESET_UPLOAD_FORM';


// Connect Device
export const DELETE_IDS = 'DELETE_IDS';
export const SYNC_IDS = 'SYNC_IDS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const RESET_ACCEPT_PASSWORD_FORM = 'RESET_ACCEPT_PASSWORD_FORM';

export const CHECK_PASS = 'CHECK_PASS';
export const CHECK_DEALER_PIN = 'CHECK_DEALER_PIN';
export const GET_DEALER_APPS = 'GET_DEALER_APPS';
export const HANDLE_CHECK_EXTENSION = 'HANDLE_CHECK_EXTENSION';
export const HANDLE_CHECK_ALL_EXTENSION = 'HANDLE_CHECK_ALL_EXTENSION';
export const HANDLE_CHECK_APP_POLICY = 'HANDLE_CHECK_APP_POLICY';
export const HANDLE_CHECK_SYSTEM_PERMISSIONS = 'HANDLE_CHECK_SYSTEM_PERMISSIONS';
export const HANDLE_CHECK_ALL_APP_POLICY = 'HANDLE_CHECK_ALL_APP_POLICY';

export const SHOW_PUSH_APPS_MODAL = 'SHOW_PUSH_APPS_MODAL';
export const UNDO_EXTENSIONS = 'UNDO_EXTENSIONS';
export const REDO_EXTENSIONS = 'REDO_EXTENSIONS';
export const HANDLE_CHECK_CONTROL = 'HANDLE_CHECK_CONTROL';
export const HANDLE_CHECK_MAIN_SETTINGS = 'HANDLE_CHECK_MAIN_SETTINGS';
export const UNDO_CONTROLS = 'UNDO_CONTROLS';
export const REDO_CONTROLS = 'REDO_CONTROLS';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const HANDLE_CHECK_APP = 'HANDLE_CHECK_APP';
export const HANDLE_CHECK_ALL = 'HANDLE_CHECK_ALL';
export const CHECK_HANDLE_ALL_POLICY = 'CHECK_HANDLE_ALL_POLICY';

export const PUSH_APPS = 'PUSH_APPS';
export const PULL_APPS = 'PULL_APPS';
export const UNDO_APPS = "UNDO_APPS";
export const REDO_APPS = 'REDO_APPS';
export const SHOW_PULL_APPS_MODAL = 'SHOW_PULL_APPS_MODAL';

export const SAVE_POLICY = 'SAVE_POLICY';
export const APPLY_POLICY = 'APPLY_POLICY';
export const POLICY_PERMSSION_SAVED = 'POLICY_PERMSSION_SAVED';

export const APPLY_SETTINGS = 'APPLY_SETTINGS';

export const SETTINGS_APPLIED = 'SETTINGS_APPLIED';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
// export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const SHOW_HISTORY_MODAL = 'SHOW_HISTORY_MODAL';
export const SHOW_SAVE_PROFILE_MODAL = 'SHOW_SAVE_PROFILE_MODAL';
export const HANDLE_PROFILE_INPUT = 'HANDLE_PROFILE_INPUT';
export const POLICY = 'policy';
export const PROFILE = 'profile';
export const SAVE_PROFILE = 'SAVE_PROFILE';
export const UNLINK_DEVICE = 'UNLINK_DEVICE';
export const HANDLE_POLICY_STATUS = 'HANDLE_POLICY_STATUS';
export const EDIT_POLICY = 'EDIT_POLICY';
export const SAVE_POLICY_CHANGES = 'SAVE_POLICY_CHANGES';
export const HIDE_POLICY_CONFIRM = 'HIDE_POLICY_CONFIRM';

export const LOADING = 'LOADING';
export const IMPORT_CSV = 'IMPORT_CSV';
export const GET_SIM_IDS = 'GET_SIM_IDS';
export const GET_CHAT_IDS = 'GET_CHAT_IDS';
export const GET_PGP_EMAILS = 'GET_PGP_EMAILS';
export const GET_USED_PGP_EMAILS = 'GET_USED_PGP_EMAILS';
export const GET_USED_CHAT_IDS = 'GET_USED_CHAT_IDS';
export const GET_USED_SIM_IDS = 'GET_USED_SIM_IDS';
export const RELEASE_CSV = 'RELEASE_CSV';
export const GET_IMIE_HISTORY = 'GET_IMIE_HISTORY';
export const WRITE_IMEI = 'WRITE_IMEI';

export const GET_SALE_LIST = 'GET_SALE_LIST';
export const GET_DEALER_LIST = 'GET_DEALER_LIST';
export const GET_DEVICE_LIST = 'GET_DEVICE_LIST';


// Policy consts
export const GET_POLICIES = 'GET_POLICIES'
export const DEFAULT_POLICY_CHANGE = 'DEFAULT_POLICY_CHANGE'


// Users consts
export const SAVE_USERS = 'SAVE_USERS'
export const EDIT_USERS = 'EDIT_USERS'
export const LOAD_USER = 'LOAD_USER'
export const USERS_LIST = 'USERS_LIST'
export const DELETE_USER = 'DELETE_USER'
export const UNDO_DELETE_USER = 'UNDO_DELETE_USER'

//App Market Constants
export const TRANSFER_APPS = 'TRANSFER_APPS'
export const GET_MARKET_APPS = 'GET_MARKET_APPS'
export const UNINSTALL_PERMISSION_CHANGED = 'UNINSTALL_PERMISSION_CHANGED'


// Socket Actions
export const FINISHED_PUSH_APPS = 'FINISHED_PUSH_APPS';
export const FINISHED_PULL_APPS = 'FINISHED_PULL_APPS';
export const FINISHED_POLICY = 'FINISHED_POLICY';
export const FINISHED_IMEI = 'FINISHED_IMEI';
export const IN_PROCESS = 'IN_PROCESS';


// WHITE LABELS CONST

export const GET_WHITE_LABEL_INFO = 'GET_WHITE_LABEL_INFO';

//Reporting
export const PRODUCT_REPORT = 'PRODUCT_REPORT';
export const INVOICE_REPORT = 'INVOICE_REPORT';
export const PAYMENT_HISTORY_REPORT = 'PAYMENT_HISTORY_REPORT';
export const HARDWARE_REPORT = 'HARDWARE_REPORT';
export const SALES_REPORT = 'SALES_REPORT';
export const GRACE_DAYS_REPORT = 'GRACE_DAYS_REPORT';

export const LATEST_PAYMENT_HISTORY = 'LATEST_PAYMENT_HISTORY';
export const GET_OVERDUE_DETAILS = 'GET_OVERDUE_DETAILS';
